####### Parameters 
J = 100
edu_types = ["H","L"]
race_types = ["White","Black"]

# Production function
gamma_HH = -0.2
gamma_HL = 0.5
gamma_LL = -0.5
gamma_LH = 0.7

# Housing demand instrument coefficients
alpha_HH = 0.8
alpha_HL = 0.1
alpha_LH = 0.2
alpha_LL = 0.7

# Housing supply 
iota = 0.05
phi = 1 
phi_geo = 0.3
phi_reg = 0.4

# Amenity supply
phi_a = 0.5

# Utility
zeta = 0.8

beta_st = 3

[beta_x]  
White = 0.3
Black = 0.7

[beta_a] 
White = 0.3
Black = 0.9

[beta_w]
White = 0.9
Black = 0.2

# Demographics
[H]
[H.Black]
N = 20
[H.White]
N = 80

[L]
[L.Black]
N = 180
[L.White]
N = 20

###### Observables
# Housing Demand Instruments
[Z_H]
mu = 0 
sigma = 0.5

[Z_L]
mu = 0
sigma = 0.5

# Housing supply 
[x_geo]
mu = 0 
sigma = 0.5

[x_reg]
mu = 0
sigma = 0.5

[CC]
mu = 0
sigma = 0.1

# Amenities
[x]
mu = 0
sigma = 0.1

###### Un-Observables
[epsilon_H]
mu = 2
sigma = 0.1

[epsilon_L]
mu = 1
sigma = 0.1

[epsilon_a]
mu = 0
sigma = 0.1