####### Parameters 
J = 50
NUM_STATES = 10

# Production function
gamma_HH = -0.2
gamma_HL = 0.5
gamma_LL = -0.5
gamma_LH = 0.7

# Housing demand instrument coefficients
alpha_HH = 0.8
alpha_HL = 0.1
alpha_LH = 0.2
alpha_LL = 0.7

# Housing supply 
iota = 0.05
phi = 1 
phi_geo = 0.3
phi_reg = 0.4

# Amenity supply
phi_a = 0.5

# Utility
beta_x  = [0.3, 0.7]
beta_a  = [0.6, 0.4]
beta_st = [0.2, 0.5]
beta_w  = [0.6, 0.5]
zeta = 0.8

# Demographics
[H]
N = 100
p_black = 0.2

[L]
N = 200
p_black = 0.9

###### Observables
# Housing Demand Instruments
[Z_H]
mu = 0 
sigma = 1

[Z_L]
mu = 0
sigma = 1

# Housing supply 
[x_geo]
mu = 0 
sigma = 1 

[x_reg]
mu = 0
sigma = 1

[CC]
mu = 0
sigma = 1

# Amenities
[x]
mu = 0
sigma = 1 

[a]
mu = 0
sigma = 1

###### Un-Observables
[epsilon_H]
mu = 2
sigma = 1

[epsilon_L]
mu = 1
sigma = 1

[epsilon_a]
mu = 0
sigma = 1